# Generated by Django 4.2 on 2026-09-15 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('fullmame', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('pho', models.CharField(max_length=10)),
            ],
        ),
    ]
